# Generated by Django 3.2.7 on 2021-10-10 22:32

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='follower_is_not_following',
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.CheckConstraint(check=models.Q(('follower', django.db.models.expressions.F('following')), _negated=True), name='follower_is_not_following'),
        ),
    ]
